# Generated by Django 4.2.7 on 2023-11-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='call',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
