# Generated by Django 4.2.7 on 2023-11-12 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_herobanner_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='call_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='description_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='description_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='secondarybanner',
            name='title_active',
            field=models.BooleanField(default=False),
        ),
    ]
