# Generated by Django 4.2.7 on 2023-11-12 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banners', '0003_herobanner_call_active_herobanner_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='secondarybanner',
            name='clicks',
        ),
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.herobanner')),
                ('clicked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
