# Generated by Django 4.2.7 on 2023-11-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_remove_herobanner_clicks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerClick',
        ),
    ]
