# Generated by Django 4.2.7 on 2023-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Meu Site', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=20)),
                ('email_host', models.CharField(blank=True, max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=100)),
                ('email_host_password', models.CharField(blank=True, max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('footer_text', models.TextField(blank=True)),
                ('terms_of_service_url', models.URLField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('payment_api_key', models.CharField(blank=True, max_length=100)),
                ('theme_color', models.CharField(default='#000000', max_length=7)),
                ('theme_font', models.CharField(default='Arial', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
            },
        ),
    ]
