# Generated by Django 4.2.7 on 2023-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_sitesettings_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_font',
            field=models.CharField(default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Itálico')], default='normal', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_font_weight',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Negrito'), ('bolder', 'Muito Negrito')], default='normal', max_length=100),
        ),
    ]
