# Generated by Django 4.2.7 on 2023-11-14 12:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_sitesettings_navbar_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
    ]
