# Generated by Django 4.2.7 on 2023-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_sitesettings_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_lateral',
            field=models.BooleanField(default=False),
        ),
    ]
