# Generated by Django 4.2.7 on 2023-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0006_sitesettings_menu_lateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banners_secundarios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrocel_departamentos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrocel_produtos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrocel_triplo',
            field=models.BooleanField(default=True),
        ),
    ]
