# Generated by Django 4.2.7 on 2023-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0007_sitesettings_banner_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_fixo',
            field=models.BooleanField(default=False),
        ),
    ]
