# Generated by Django 4.2.7 on 2023-11-18 10:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0008_sitesettings_navbar_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background',
            field=colorfield.fields.ColorField(default='#f5f5f5', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header',
            field=colorfield.fields.ColorField(default='#f5f5f5', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_secundario',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_navbar_icons',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_navbar_icons_circle_background',
            field=colorfield.fields.ColorField(default='#dc3545', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_navbar_icons_circle_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_icons',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_icons_circle_background',
            field=colorfield.fields.ColorField(default='#dc3545', image_field=None, max_length=7, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_icons_circle_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
    ]
