# Generated by Django 4.2.7 on 2023-11-18 10:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0009_sitesettings_footer_background_sitesettings_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#1c1c1c', image_field=None, max_length=7, samples=None),
        ),
    ]
