# Generated by Django 4.2.7 on 2023-11-18 11:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0010_sitesettings_footer_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobili_header_secundario',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
    ]
