# Generated by Django 4.2.7 on 2023-11-22 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0017_productreview'),
        ('sessions', '0001_initial'),
        ('usuario', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='usuario.userprofile')),
            ],
            options={
                'verbose_name': 'shopping cart',
                'verbose_name_plural': 'shopping carts',
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximo_usos', models.IntegerField(default=1)),
                ('usos_atuais', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Expirado', 'Expirado'), ('Utilizado', 'Utilizado')], default='Ativo', max_length=15)),
                ('data_validade', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('estados_frete_gratis', models.CharField(blank=True, help_text='Estados para frete grátis, separados por vírgula', max_length=100, null=True)),
                ('max_uso_por_cliente', models.PositiveIntegerField(blank=True, default=None, help_text='Máximo de uso por cliente. Deixe em branco ou coloque None para uso ilimitado.', null=True)),
                ('tipo_de_frete_gratis', models.CharField(blank=True, help_text='Escolha o tipo de fretes que seram gratis, separados por vírgula', max_length=100, null=True)),
                ('desconto_percentual_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('desconto_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categorias_aplicaveis', models.ManyToManyField(blank=True, to='products.category')),
                ('produtos_aplicaveis', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrinho.shoppingcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'shopping cart item',
                'verbose_name_plural': 'shopping cart items',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
