# Generated by Django 4.2.7 on 2023-11-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productreview'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
