# Generated by Django 4.2.7 on 2023-11-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productreview'),
        ('carrinho', '0002_shoppingcartitem_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'product', 'variation')},
        ),
    ]
