# Generated by Django 4.2.7 on 2023-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_shipping_zipcode_order_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cpf_destinatario',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
