# Generated by Django 4.2.7 on 2023-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_order_cpf_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_pedido',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
