# Generated by Django 4.2.7 on 2023-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_order_email_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rastreio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_frete',
            field=models.CharField(default='PAC', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
