# Generated by Django 4.2.7 on 2023-11-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('newsletter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_history', models.JSONField(blank=True, null=True)),
                ('product_preferences', models.JSONField(blank=True, null=True)),
                ('browsing_history', models.JSONField(blank=True, null=True)),
                ('marketing_responses', models.JSONField(blank=True, null=True)),
                ('customer_service_interactions', models.JSONField(blank=True, null=True)),
                ('income_range', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('reward_status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='usuario.userprofile')),
            ],
            options={
                'verbose_name': 'user page visit',
                'verbose_name_plural': 'user page visits',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='usuario.userprofile')),
            ],
            options={
                'verbose_name': 'user login history',
                'verbose_name_plural': 'user login histories',
            },
        ),
    ]
