# Generated by Django 4.2.7 on 2023-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_address_bairro_address_complemento_address_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='destinatario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
