# Generated by Django 4.2.7 on 2023-11-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('usuario', '0007_alter_address_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_addresses', to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='usuario.userprofile'),
        ),
    ]
