# Generated by Django 4.2.7 on 2023-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_address_session_alter_address_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cpf_destinatario',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
