# Generated by Django 4.2.7 on 2023-12-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0010_alter_address_options'),
        ('products', '0023_alter_category_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AviseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_on', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avise', to='usuario.userprofile')),
            ],
        ),
    ]
