# Generated by Django 4.2.7 on 2023-12-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_department'),
        ('avise', '0002_alter_aviseitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
