# Generated by Django 4.2.7 on 2023-11-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_category_category_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sells',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
