# Generated by Django 4.2.7 on 2023-11-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='image',
            new_name='image_department',
        ),
    ]
