# Generated by Django 4.2.7 on 2023-11-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_slug_department_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
