# Generated by Django 4.2.7 on 2023-11-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_slug_department_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMapeamento', models.CharField(max_length=255)),
                ('skuMapeamento', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(max_length=255)),
                ('gtin', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precoPromocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoqueAtual', models.IntegerField()),
                ('grade', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
        ),
    ]
