# Generated by Django 4.2.7 on 2023-11-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='precoPromocional',
            new_name='promocional_price',
        ),
    ]
