# Generated by Django 4.2.7 on 2023-11-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_preco_productvariation_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='promocional_price',
            new_name='promotional_price',
        ),
    ]
