# Generated by Django 4.2.7 on 2023-11-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_promocional_price_productvariation_promotional_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['price']},
        ),
    ]
