# Generated by Django 4.2.7 on 2023-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_materiaprima_productvariationrawmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='gtin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
